#全向
odom2camera:
  xyz: "\"0.06 0.0  0.035\""
  rpy: "\"0.0  0.0  0.0\""

# #sentry
# odom2camera:
#   xyz: "\"0.09 0.0  0.03\""
#   rpy: "\"0.0  0.0  0.0\""

# 设置启动参数 
# 命名空间 所有节点、话题都会以这个命名空间开头，如/some_namespace/image_raw
namespace: ''
# true: 读取视频 false: 读取相机
video_play: false
# true: 虚拟下位机 false: 实车 
virtual_serial: false 
# true: 英雄解算 false: 传统解算
hero_solver: false
# true: 开启打符 false：关闭打符
rune: false
# true: 启动导航tf false：不启动导航tf
navigation: false
# true: 使用传统视觉 false：使用神经网络
mode: true
# true: 使用海康相机 false：使用迈德相机
camera: true
